version: '3.9'

services:
  ndrdb:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ndr
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ndr:
    image: ghcr.io/prehisle/ndr-service:latest
    environment:
      DB_URL: postgresql+psycopg2://postgres:postgres@ndrdb:5432/ndr
      AUTO_APPLY_MIGRATIONS: "true"
      # 可按需设置 API Key 等相关环境变量，例如：
      # API_KEY: your-key
    ports:
      - "8000:8000"
    depends_on:
      ndrdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/openapi.json >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

# 使用说明：
# 1) 启动：docker compose -f deploy/dev/docker-compose.ndr.yml up -d
# 2) 后端配置：导出 YDMS_NDR_BASE_URL=http://localhost:8000 后启动后端
# 3) 验证：curl http://localhost:8000/openapi.json
