// Code generated by docgen; DO NOT EDIT.
package service

func init() {
	documentTypeDefinitions = map[DocumentType]DocumentTypeDefinition{
		DocumentType("comprehensive_choice_v1"): {
			ID: DocumentType("comprehensive_choice_v1"),
			Label: "综合知识选择题(v1)",
			ContentFormat: ContentFormatYAML,
			TemplatePath: "../../../doc-types/comprehensive_choice_v1/template.yaml",
		},
		DocumentType("case_analysis_v1"): {
			ID: DocumentType("case_analysis_v1"),
			Label: "案例分析题(v1)",
			ContentFormat: ContentFormatYAML,
			TemplatePath: "../../../doc-types/case_analysis_v1/template.yaml",
		},
		DocumentType("essay_v1"): {
			ID: DocumentType("essay_v1"),
			Label: "论文题(v1)",
			ContentFormat: ContentFormatYAML,
			TemplatePath: "../../../doc-types/essay_v1/template.yaml",
		},
		DocumentType("dictation_v1"): {
			ID: DocumentType("dictation_v1"),
			Label: "默写(v1)",
			ContentFormat: ContentFormatYAML,
			TemplatePath: "../../../doc-types/dictation_v1/template.yaml",
		},
		DocumentType("knowledge_overview_v1"): {
			ID: DocumentType("knowledge_overview_v1"),
			Label: "知识点概览(v1)",
			ContentFormat: ContentFormatHTML,
			TemplatePath: "../../../doc-types/knowledge_overview_v1/template.html",
		},
	}
	documentTypeOrder = []DocumentType{
		DocumentType("comprehensive_choice_v1"),
		DocumentType("case_analysis_v1"),
		DocumentType("essay_v1"),
		DocumentType("dictation_v1"),
		DocumentType("knowledge_overview_v1"),
	}
}
