types:
  - id: overview
    label: "概览"
    content_format: "html"
    template: "template.html"
  - id: dictation
    label: "默写"
    content_format: "yaml"
    template: "template.yaml"
    frontend:
      hook_import: "../features/documents/typePlugins/dictation/register"
  - id: comprehensive_choice
    label: "综合选择题"
    content_format: "yaml"
    template: "template.yaml"
    frontend:
      hook_import: "../features/documents/typePlugins/comprehensiveChoice/register"
  - id: case_analysis
    label: "案例分析题"
    content_format: "yaml"
    template: "template.yaml"
    frontend:
      hook_import: "../features/documents/typePlugins/caseAnalysis/register"
  - id: essay
    label: "论文题"
    content_format: "yaml"
    template: "template.yaml"
    frontend:
      hook_import: "../features/documents/typePlugins/essay/register"
  - id: comprehensive_choice_v1
    label: "综合知识选择题(v1)"
    content_format: "yaml"
    template: "template.yaml"
    frontend:
      hook_import: "../features/documents/typePlugins/comprehensiveChoiceV1/register"
  - id: case_analysis_v1
    label: "案例分析题(v1)"
    content_format: "yaml"
    template: "template.yaml"
    frontend:
      hook_import: "../features/documents/typePlugins/case_analysis_v1/register"
  - id: essay_v1
    label: "论文题(v1)"
    content_format: "yaml"
    template: "template.yaml"
    frontend:
      hook_import: "../features/documents/typePlugins/essay_v1/register"
  - id: dictation_v1
    label: "默写(v1)"
    content_format: "yaml"
    template: "template.yaml"
    frontend:
      hook_import: "../features/documents/typePlugins/dictation_v1/register"
  - id: knowledge_overview_v1
    label: "知识点概览(v1)"
    content_format: "html"
    template: "template.html"
    frontend:
      hook_import: "../features/documents/typePlugins/knowledge_overview_v1/register"
      themes:
        - id: "glass"
          label: "玻璃拟态"
          description: "半透明蓝紫色，强调高光与模糊"
          path: "themes/glass.css"
        - id: "forest"
          label: "竹林墨韵"
          description: "墨绿色调，适合国风内容"
          path: "themes/forest.css"
  - id: chapter_overview_v1
    label: "章节概览(v1)"
    content_format: "html"
    template: "template.html"
    frontend:
      hook_import: "../features/documents/typePlugins/chapter_overview_v1/register"
      themes:
        - id: "glass"
          label: "玻璃拟态"
          description: "半透明蓝紫色，强调高光与模糊"
          path: "themes/glass.css"
        - id: "forest"
          label: "竹林墨韵"
          description: "墨绿色调，适合国风内容"
          path: "themes/forest.css"
