name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (Go)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Go version
        run: go version
      - name: Download deps
        run: go mod download
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build ./...
      - name: Run unit tests
        run: go test ./... -cover -covermode=atomic -coverprofile=coverage.out -count=1
      - name: Upload Go coverage
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage
          path: backend/coverage.out

      - name: golangci-lint (non-blocking for initial adoption)
        uses: golangci/golangci-lint-action@v6
        continue-on-error: true
        with:
          version: latest
          working-directory: backend

  frontend:
    name: Frontend (Node)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run typecheck
      - name: Run unit tests
        run: npm run test:coverage
      - name: Upload Frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
      - name: Build
        run: npm run build
